msg_start = "Hello! \nI am your climate control bot. I can provide information about the clime in your home. I will also sometimes ask how you feel. For more info enter command /help"
msg_help = "This is help."
msg_echo = "Sorry. I don't understand you."
msg_feel_GOOD = "Glad you're OK!"
msg_feel_BAD = "Oh, I'm sorry 😥\nGo have some tea"
msg_feel_SEND = "Sending your reply to the server..."
msg_feel_DISCARD = "OK, tell me one more time how you feel"